### ISSUE TITLE
Cache control is set to private if no s-maxage directive is present.

### ISSUE THREAD

**Issue by DieterHolvoet** [wieni/wmpage_cache#20]
I don't need an s-maxage directive since my CDN (Bunny) doesn't seem to use it. But when I get rid of the directive in my `wmpage_cache.expiry` config, the private directive is automatically added by Symfony:

```php
# Symfony\Component\HttpFoundation\ResponseHeaderBag::computeCacheControlValue

$header = $this->getCacheControlHeader();
if (isset($this->cacheControl['public']) || isset($this->cacheControl['private'])) {
    return $header;
}

// public if s-maxage is defined, private otherwise
if (!isset($this->cacheControl['s-maxage'])) {
    return $header.', private';
}
```

I tried adding `public` to the `wmpage_cache.expiry` config, but that doesn't seem to work:
```
wmpage_cache.expiry:
    entities:
        node:
            _default: { public: true, maxage: 31536000, wm-s-maxage: 86400 }
```

So either we make that work, or we set the public directive ourselves if a maxage is set - which makes more sense IMO.
